name: static_route
description: Provide statically registered page navigation template library.

version: 2.1.2

homepage: https://github.com/cwkProject/static_route

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
