name: static_route
description: Provide statically registered page navigation template library.

version: 1.0.1

homepage: https://github.com/cwkProject/static_route
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
