name: static_route
description: Provide statically registered page navigation template library.

version: 2.1.0

homepage: https://github.com/cwkProject/static_route
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
